name: slim
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - dm-sonnet=1.36
  - ffmpeg=4.0
  - joblib=0.14.1
  - keras=2.3.1
  - numpy=1.18.1
  - pillow=7.0.0
  - pip=20.0.2
  - py-opencv=3.4.2
  - python=3.7.7
  - scipy=1.4.1
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tqdm=4.44.1
  - youtube-dl=2020.3.24
  - pip:
    - opencv-python==4.2.0.34
